### ISSUE TITLE
New URL

### ISSUE THREAD

**Issue by bouncenz** [tylerdave/bloomsky-api#1]
Hi,  

Nice work with the API.

Looks like the BloomSky API URL has changed to:
https://api.bloomsky.com/api/skydata/

Works when you supply the URL to override the default.
client = bloomsky_api.BloomSkyAPIClient(api_key='wibble', api_url='https://api.bloomsky.com/api/skydata/')

Steve

**Comment by tylerdave** [comment]
Thanks for the info! Can you tell me where you found the new URL?

(I ask because the dashboard still shows me https://thirdpartyapi.appspot.com/api/skydata/ under the 'Developers' link)

It seems to work for me with either URL but I'll update it to the new one if that's official.

**Comment by bouncenz** [comment]
Yes I saw the dashboard still had the old URL.
I found it in the BloomSky forums when I went looking because with the API I kept getting 401 unauthorised.
I think the API doc has been updated too with the new URL  

Cheers,
Steve
